[package]
name = "interstice-adapters"
version = "0.1.0"
edition = "2021"

[dependencies]
# Internal
interstice-core = { path = "../interstice-core" }
interstice-ml = { path = "../interstice-ml" }

# Workspace
tokio = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
reqwest = { workspace = true }
tracing = { workspace = true }
slack-morphism = { workspace = true, features = ["hyper"] }
sqlx = { workspace = true }

# Additional dependencies
uuid = { workspace = true }
chrono = { workspace = true }
dashmap = "6.1.0"
futures = "0.3.31"

[features]
default = ["full-slack"]
simple-slack = []
full-slack = []